#!/bin/bash

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Generating formatted reports...${NC}"

# Read summary data
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
STATUS="UNKNOWN"

if [ -f "test_results/summary.txt" ]; then
    TOTAL_TESTS=$(grep "Total tests:" test_results/summary.txt | awk '{print $3}')
    PASSED_TESTS=$(grep "Passed:" test_results/summary.txt | awk '{print $2}')
    FAILED_TESTS=$(grep "Failed:" test_results/summary.txt | awk '{print $2}')
    STATUS=$(grep "Status:" test_results/summary.txt | awk '{print $2}')
fi

# Get timestamp
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S UTC")
COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse HEAD 2>/dev/null || echo 'unknown')}"
COMMIT_SHORT="${COMMIT_SHA:0:7}"

# ============================================
# Generate Markdown Report
# ============================================
cat > test_results/summary.md << EOF
# Test Results Summary

**Date:** $TIMESTAMP  
**Commit:** \`$COMMIT_SHORT\`  
**Status:** $([ "$STATUS" = "SUCCESS" ] && echo "✅ PASSED" || echo "❌ FAILED")

## Overview

| Metric | Count |
|--------|-------|
| Total Tests | $TOTAL_TESTS |
| Passed | $PASSED_TESTS ✅ |
| Failed | $FAILED_TESTS ❌ |
| Success Rate | $([ $TOTAL_TESTS -gt 0 ] && echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc || echo "0")% |

## Detailed Results

EOF

# Add individual test results to markdown
for log_file in test_results/*_actual.out; do
    if [ -f "$log_file" ]; then
        base_name=$(basename "$log_file" _actual.out)
        test_name=$(echo "$base_name" | sed 's/_/ /g')
        
        # Check if test passed or failed
        diff_file="test_results/${base_name}_diff.txt"
        if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
            # Test failed
            cat >> test_results/summary.md << EOF
### ❌ $test_name

**Status:** Failed

<details>
<summary>View Diff</summary>

\`\`\`diff
$(head -20 "$diff_file")
\`\`\`

</details>

EOF
        else
            # Test passed
            cat >> test_results/summary.md << EOF
### ✅ $test_name

**Status:** Passed

EOF
        fi
    fi
done

cat >> test_results/summary.md << EOF

---

*Generated by GitHub Actions*
EOF

echo -e "${GREEN}✓ Markdown report generated: test_results/summary.md${NC}"

# ============================================
# Generate LaTeX Report
# ============================================
cat > test_results/report.tex << 'EOF'
\documentclass[11pt,a4paper]{article}
\usepackage[margin=1in]{geometry}
\usepackage{xcolor}
\usepackage{listings}
\usepackage{booktabs}
\usepackage{hyperref}

\definecolor{passcode}{HTML}{2ECC71}
\definecolor{failcode}{HTML}{E74C3C}

\title{Automated Test Results Report}
\author{GitHub Actions}
\date{TIMESTAMP_PLACEHOLDER}

\begin{document}

\maketitle

\section{Summary}

\begin{table}[h]
\centering
\begin{tabular}{lr}
\toprule
\textbf{Metric} & \textbf{Count} \\
\midrule
Commit & \texttt{COMMIT_PLACEHOLDER} \\
Total Tests & TOTAL_PLACEHOLDER \\
\textcolor{passcode}{Passed} & PASSED_PLACEHOLDER \\
\textcolor{failcode}{Failed} & FAILED_PLACEHOLDER \\
Success Rate & RATE_PLACEHOLDER\% \\
\bottomrule
\end{tabular}
\end{table}

\subsection{Overall Status}

STATUS_PLACEHOLDER

\section{Detailed Results}

EOF

# Add test details
for log_file in test_results/*_actual.out; do
    if [ -f "$log_file" ]; then
        base_name=$(basename "$log_file" _actual.out)
        test_name=$(echo "$base_name" | sed 's/_/\\_/g')
        
        diff_file="test_results/${base_name}_diff.txt"
        if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
            cat >> test_results/report.tex << EOF
\subsection*{\textcolor{failcode}{$test_name - FAILED}}

EOF
        else
            cat >> test_results/report.tex << EOF
\subsection*{\textcolor{passcode}{$test_name - PASSED}}

EOF
        fi
    fi
done

cat >> test_results/report.tex << 'EOF'

\end{document}
EOF

# Replace placeholders
sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" test_results/report.tex
sed -i "s/COMMIT_PLACEHOLDER/$COMMIT_SHORT/g" test_results/report.tex
sed -i "s/TOTAL_PLACEHOLDER/$TOTAL_TESTS/g" test_results/report.tex
sed -i "s/PASSED_PLACEHOLDER/$PASSED_TESTS/g" test_results/report.tex
sed -i "s/FAILED_PLACEHOLDER/$FAILED_TESTS/g" test_results/report.tex

SUCCESS_RATE=$([ $TOTAL_TESTS -gt 0 ] && echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc || echo "0")
sed -i "s/RATE_PLACEHOLDER/$SUCCESS_RATE/g" test_results/report.tex

if [ "$STATUS" = "SUCCESS" ]; then
    sed -i "s/STATUS_PLACEHOLDER/\\\\textcolor{passcode}{\\\\textbf{All tests passed!}}/g" test_results/report.tex
else
    sed -i "s/STATUS_PLACEHOLDER/\\\\textcolor{failcode}{\\\\textbf{Some tests failed.}}/g" test_results/report.tex
fi

echo -e "${GREEN}✓ LaTeX report generated: test_results/report.tex${NC}"

# Try to compile to PDF if pdflatex is available
if command -v pdflatex &> /dev/null; then
    cd test_results
    pdflatex -interaction=nonstopmode report.tex > /dev/null 2>&1
    pdflatex -interaction=nonstopmode report.tex > /dev/null 2>&1  # Run twice for TOC
    cd ..
    if [ -f "test_results/report.pdf" ]; then
        echo -e "${GREEN}✓ PDF report generated: test_results/report.pdf${NC}"
    fi
fi

# ============================================
# Generate Typst Report
# ============================================
cat > test_results/report.typ << 'EOF'
#set document(title: "Test Results Report", author: "GitHub Actions")
#set page(numbering: "1", margin: 1in)
#set text(font: "Linux Libertine", size: 11pt)

#align(center)[
  #text(size: 20pt, weight: "bold")[Automated Test Results Report]
  
  #v(0.5em)
  
  #text(size: 12pt)[GitHub Actions]
  
  #v(0.5em)
  
  #text(size: 10pt)[TIMESTAMP_PLACEHOLDER]
]

#v(1em)

= Summary

#table(
  columns: (auto, auto),
  align: left,
  [*Metric*], [*Count*],
  [Commit], [`COMMIT_PLACEHOLDER`],
  [Total Tests], [TOTAL_PLACEHOLDER],
  [Passed], [#text(fill: green)[PASSED_PLACEHOLDER ✓]],
  [Failed], [#text(fill: red)[FAILED_PLACEHOLDER ✗]],
  [Success Rate], [RATE_PLACEHOLDER%],
)

#v(1em)

== Overall Status

STATUS_PLACEHOLDER

#v(1em)

= Detailed Results

#v(0.5em)

EOF

# Add test details to Typst
for log_file in test_results/*_actual.out; do
    if [ -f "$log_file" ]; then
        base_name=$(basename "$log_file" _actual.out)
        test_name=$(echo "$base_name" | sed 's/_/ /g')
        
        diff_file="test_results/${base_name}_diff.txt"
        if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
            cat >> test_results/report.typ << EOF
== #text(fill: red)[$test_name - FAILED]

EOF
        else
            cat >> test_results/report.typ << EOF
== #text(fill: green)[$test_name - PASSED]

EOF
        fi
    fi
done

# Replace placeholders in Typst
sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/g" test_results/report.typ
sed -i "s/COMMIT_PLACEHOLDER/$COMMIT_SHORT/g" test_results/report.typ
sed -i "s/TOTAL_PLACEHOLDER/$TOTAL_TESTS/g" test_results/report.typ
sed -i "s/PASSED_PLACEHOLDER/$PASSED_TESTS/g" test_results/report.typ
sed -i "s/FAILED_PLACEHOLDER/$FAILED_TESTS/g" test_results/report.typ
sed -i "s/RATE_PLACEHOLDER/$SUCCESS_RATE/g" test_results/report.typ

if [ "$STATUS" = "SUCCESS" ]; then
    sed -i "s/STATUS_PLACEHOLDER/#text(fill: green, weight: \"bold\")[All tests passed!]/g" test_results/report.typ
else
    sed -i "s/STATUS_PLACEHOLDER/#text(fill: red, weight: \"bold\")[Some tests failed.]/g" test_results/report.typ
fi

echo -e "${GREEN}✓ Typst report generated: test_results/report.typ${NC}"

# Try to compile Typst to PDF if typst is available
if command -v typst &> /dev/null; then
    typst compile test_results/report.typ test_results/report-typst.pdf > /dev/null 2>&1
    if [ -f "test_results/report-typst.pdf" ]; then
        echo -e "${GREEN}✓ Typst PDF report generated: test_results/report-typst.pdf${NC}"
    fi
fi

# Save status for workflow
echo "$STATUS" > test_results/status.txt

echo -e "${GREEN}Report generation complete!${NC}"
