#!/bin/bash

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Generating formatted reports...${NC}"

# Get timestamp
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S UTC")
COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse HEAD 2>/dev/null || echo 'unknown')}"
COMMIT_SHORT="${COMMIT_SHA:0:7}"

# ============================================
# Generate Per-Folder Markdown Reports
# ============================================

# Find all subdirectories in test_results (each corresponds to a source folder)
for source_dir in test_results/*/; do
    if [ -d "$source_dir" ]; then
        # Extract the original source path
        source_path="${source_dir#test_results/}"
        source_path="${source_path%/}"
        
        # Count tests for this folder
        FOLDER_TOTAL=0
        FOLDER_PASSED=0
        FOLDER_FAILED=0
        
        # Count test results in this folder
        for actual_file in "${source_dir}"*_actual.out; do
            if [ -f "$actual_file" ]; then
                FOLDER_TOTAL=$((FOLDER_TOTAL + 1))
                
                base_name=$(basename "$actual_file" _actual.out)
                diff_file="${source_dir}${base_name}_diff.txt"
                
                if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
                    FOLDER_FAILED=$((FOLDER_FAILED + 1))
                else
                    FOLDER_PASSED=$((FOLDER_PASSED + 1))
                fi
            fi
        done
        
        # Only create report if tests were run
        if [ $FOLDER_TOTAL -gt 0 ]; then
            FOLDER_STATUS=$([ $FOLDER_FAILED -eq 0 ] && echo "PASSED" || echo "FAILED")
            
            cat > "${source_dir}SUMMARY.md" << EOF
# Test Results: \`$source_path\`

**Date:** $TIMESTAMP  
**Commit:** \`$COMMIT_SHORT\`  
**Status:** $([ "$FOLDER_STATUS" = "PASSED" ] && echo "✅ PASSED" || echo "❌ FAILED")

## Overview

| Metric | Count |
|--------|-------|
| Total Tests | $FOLDER_TOTAL |
| Passed | $FOLDER_PASSED ✅ |
| Failed | $FOLDER_FAILED ❌ |
| Success Rate | $([ $FOLDER_TOTAL -gt 0 ] && echo "scale=1; $FOLDER_PASSED * 100 / $FOLDER_TOTAL" | bc || echo "0")% |

## Test Details

EOF

            # Add individual test results
            for actual_file in "${source_dir}"*_actual.out; do
                if [ -f "$actual_file" ]; then
                    base_name=$(basename "$actual_file" _actual.out)
                    test_name=$(echo "$base_name" | sed 's/_/ /g')
                    
                    diff_file="${source_dir}${base_name}_diff.txt"
                    if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
                        cat >> "${source_dir}SUMMARY.md" << EOF
### ❌ $test_name

**Status:** Failed

<details>
<summary>View Diff</summary>

\`\`\`diff
$(head -20 "$diff_file")
\`\`\`

</details>

EOF
                    else
                        cat >> "${source_dir}SUMMARY.md" << EOF
### ✅ $test_name

**Status:** Passed

EOF
                    fi
                fi
            done
            
            cat >> "${source_dir}SUMMARY.md" << EOF

---

*Generated by GitHub Actions*
EOF
            
            echo -e "${GREEN}✓ Report generated: ${source_dir}SUMMARY.md${NC}"
        fi
    fi
done

# ============================================
# Generate Global Markdown Report
# ============================================

# Read summary data from the main summary file (current run only)
CURRENT_TOTAL_TESTS=0
CURRENT_PASSED_TESTS=0
CURRENT_FAILED_TESTS=0
STATUS="UNKNOWN"

if [ -f "test_results/summary.txt" ]; then
    CURRENT_TOTAL_TESTS=$(grep "Total tests:" test_results/summary.txt | awk '{print $3}')
    CURRENT_PASSED_TESTS=$(grep "Passed:" test_results/summary.txt | awk '{print $2}')
    CURRENT_FAILED_TESTS=$(grep "Failed:" test_results/summary.txt | awk '{print $2}')
    STATUS=$(grep "Status:" test_results/summary.txt | awk '{print $2}')
fi

# Calculate aggregated totals (current + cached)
TOTAL_TESTS=$CURRENT_TOTAL_TESTS
PASSED_TESTS=$CURRENT_PASSED_TESTS
FAILED_TESTS=$CURRENT_FAILED_TESTS

# Track which folders were tested in this run (have _actual.out files)
TESTED_FOLDERS=""

cat > test_results/summary.md << EOF
# Test Results Summary

**Date:** $TIMESTAMP  
**Commit:** \`$COMMIT_SHORT\`  

## Overview

| Metric | Count |
|--------|-------|
| Tests (This Run) | $CURRENT_TOTAL_TESTS |
| Passed (This Run) | $CURRENT_PASSED_TESTS ✅ |
| Failed (This Run) | $CURRENT_FAILED_TESTS ❌ |

## Results by Source File

### This Run

EOF

if [ $CURRENT_TOTAL_TESTS -eq 0 ]; then
    cat >> test_results/summary.md << EOF
No tests were run in this commit.

EOF
fi

# Add results grouped by source folder (current run)
for source_dir in test_results/*/; do
    if [ -d "$source_dir" ]; then
        source_path="${source_dir#test_results/}"
        source_path="${source_path%/}"
        
        # Check if this folder was tested in current run (has _actual.out files)
        if ls "${source_dir}"*_actual.out 1> /dev/null 2>&1; then
            TESTED_FOLDERS="$TESTED_FOLDERS $source_dir"
            
            # Count tests for this folder
            FOLDER_TOTAL=0
            FOLDER_PASSED=0
            FOLDER_FAILED=0
            
            for actual_file in "${source_dir}"*_actual.out; do
                if [ -f "$actual_file" ]; then
                    FOLDER_TOTAL=$((FOLDER_TOTAL + 1))
                    
                    base_name=$(basename "$actual_file" _actual.out)
                    diff_file="${source_dir}${base_name}_diff.txt"
                    
                    if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
                        FOLDER_FAILED=$((FOLDER_FAILED + 1))
                    else
                        FOLDER_PASSED=$((FOLDER_PASSED + 1))
                    fi
                fi
            done
            
            FOLDER_STATUS=$([ $FOLDER_FAILED -eq 0 ] && echo "✅" || echo "❌")
            
            cat >> test_results/summary.md << EOF
#### $FOLDER_STATUS \`$source_path\`

| Tests | Passed | Failed |
|-------|--------|--------|
| $FOLDER_TOTAL | $FOLDER_PASSED | $FOLDER_FAILED |

[View detailed results]($source_path/SUMMARY.md)

EOF
        fi
    fi
done

# Add cached results (folders with SUMMARY.md but no _actual.out files from this run)
HAS_CACHED=0
for source_dir in test_results/*/; do
    if [ -d "$source_dir" ]; then
        source_path="${source_dir#test_results/}"
        source_path="${source_path%/}"
        
        # Check if folder has SUMMARY.md but wasn't tested in current run
        if [ -f "${source_dir}SUMMARY.md" ] && ! echo "$TESTED_FOLDERS" | grep -q "$source_dir"; then
            if [ $HAS_CACHED -eq 0 ]; then
                cat >> test_results/summary.md << EOF

### Cached Results (From Previous Runs)

EOF
                HAS_CACHED=1
            fi
            
            # Count tests for this folder from cached results
            FOLDER_TOTAL=0
            FOLDER_PASSED=0
            FOLDER_FAILED=0
            
            for actual_file in "${source_dir}"*_actual.out; do
                if [ -f "$actual_file" ]; then
                    FOLDER_TOTAL=$((FOLDER_TOTAL + 1))
                    
                    base_name=$(basename "$actual_file" _actual.out)
                    diff_file="${source_dir}${base_name}_diff.txt"
                    
                    if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
                        FOLDER_FAILED=$((FOLDER_FAILED + 1))
                    else
                        FOLDER_PASSED=$((FOLDER_PASSED + 1))
                    fi
                fi
            done
            
            FOLDER_STATUS=$([ $FOLDER_FAILED -eq 0 ] && echo "✅" || echo "❌")
            
            # Get timestamp from folder (try to extract from SUMMARY.md)
            FOLDER_DATE=$(grep "^**Date:**" "${source_dir}SUMMARY.md" 2>/dev/null | sed 's/.*Date: //' | sed 's/ .*//' || echo "unknown date")
            
            cat >> test_results/summary.md << EOF
#### $FOLDER_STATUS \`$source_path\` _(${FOLDER_DATE})_

| Tests | Passed | Failed |
|-------|--------|--------|
| $FOLDER_TOTAL | $FOLDER_PASSED | $FOLDER_FAILED |

[View detailed results]($source_path/SUMMARY.md)

EOF
            
            # Add to aggregated totals
            TOTAL_TESTS=$((TOTAL_TESTS + FOLDER_TOTAL))
            PASSED_TESTS=$((PASSED_TESTS + FOLDER_PASSED))
            FAILED_TESTS=$((FAILED_TESTS + FOLDER_FAILED))
        fi
    fi
done

cat >> test_results/summary.md << EOF

---

## Aggregated Statistics (Current + Cached)

| Metric | Count |
|--------|-------|
| **Total Tests** | **$TOTAL_TESTS** |
| **Passed** | **$PASSED_TESTS ✅** |
| **Failed** | **$FAILED_TESTS ❌** |
| **Success Rate** | **$([ $TOTAL_TESTS -gt 0 ] && echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc || echo "0")%** |

*Generated by GitHub Actions*
EOF

echo -e "${GREEN}✓ Markdown report generated: test_results/summary.md${NC}"

# Save status for workflow
echo "$STATUS" > test_results/status.txt

echo -e "${GREEN}Report generation complete!${NC}"
