#!/bin/bash

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Generating formatted reports...${NC}"

# Read summary data
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
STATUS="UNKNOWN"

if [ -f "test_results/summary.txt" ]; then
    TOTAL_TESTS=$(grep "Total tests:" test_results/summary.txt | awk '{print $3}')
    PASSED_TESTS=$(grep "Passed:" test_results/summary.txt | awk '{print $2}')
    FAILED_TESTS=$(grep "Failed:" test_results/summary.txt | awk '{print $2}')
    STATUS=$(grep "Status:" test_results/summary.txt | awk '{print $2}')
fi

# Get timestamp
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S UTC")
COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse HEAD 2>/dev/null || echo 'unknown')}"
COMMIT_SHORT="${COMMIT_SHA:0:7}"

# ============================================
# Generate Markdown Report
# ============================================
cat > test_results/summary.md << EOF
# Test Results Summary

**Date:** $TIMESTAMP  
**Commit:** \`$COMMIT_SHORT\`  
**Status:** $([ "$STATUS" = "SUCCESS" ] && echo "✅ PASSED" || echo "❌ FAILED")

## Overview

| Metric | Count |
|--------|-------|
| Total Tests | $TOTAL_TESTS |
| Passed | $PASSED_TESTS ✅ |
| Failed | $FAILED_TESTS ❌ |
| Success Rate | $([ $TOTAL_TESTS -gt 0 ] && echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc || echo "0")% |

## Detailed Results

EOF

# Add individual test results to markdown
for log_file in test_results/*_actual.out; do
    if [ -f "$log_file" ]; then
        base_name=$(basename "$log_file" _actual.out)
        test_name=$(echo "$base_name" | sed 's/_/ /g')
        
        # Check if test passed or failed
        diff_file="test_results/${base_name}_diff.txt"
        if [ -f "$diff_file" ] && [ -s "$diff_file" ]; then
            # Test failed
            cat >> test_results/summary.md << EOF
### ❌ $test_name

**Status:** Failed

<details>
<summary>View Diff</summary>

\`\`\`diff
$(head -20 "$diff_file")
\`\`\`

</details>

EOF
        else
            # Test passed
            cat >> test_results/summary.md << EOF
### ✅ $test_name

**Status:** Passed

EOF
        fi
    fi
done

cat >> test_results/summary.md << EOF

---

*Generated by GitHub Actions*
EOF

echo -e "${GREEN}✓ Markdown report generated: test_results/summary.md${NC}"

# Save status for workflow
echo "$STATUS" > test_results/status.txt

echo -e "${GREEN}Report generation complete!${NC}"
